---
- name: Re-run init scripts to apply config changes
  command: |
    {{ postgres_ha_service_path }}/admin.sh -f {{ item.dest }}
  loop:
    - "{{ postgres_ha_init_system }}"
    - "{{ postgres_ha_init_db }}"
  when: item.changed
  loop_control:
    label: '{{ item.dest | default("unknown") }}'
